- hosts: DEE-Cluster
  gather_facts: yes
  roles:
   - { role: common, when: configure_env }
   - { role: ntp, when: configure_env }
   - {role: 'firewall', tags: 'firewall'}
   - {role: 'storage', tags: 'storage'}
   - {role: 'docker', tags: 'docker'}
- hosts: UCP-Initial
  gather_facts: yes
  roles:
   - UCP-Initial
- hosts: UCP-Replicas
  gather_facts: yes
  roles:
   - UCP-Replica
- hosts: DTR-Initial
  gather_facts: yes
  roles:
   - DTR-Initial
- hosts: DTR-Replicas
  gather_facts: yes
  roles:
   - DTR-Replica
- hosts: DEE-Workers
  gather_facts: yes
  roles:
   - DEE-Worker
