- name: Copy deamon config file
  copy:
    src=rh-daemon.json dest=/etc/docker/daemon.json
- name: Store EE repository URL
  shell:
    echo {{dee_url}}/centos > /etc/yum/vars/dockerurl
  args:
    creates: /etc/yum/vars/dockerurl
- name: Store RHEL version for Docker
  shell:
    echo "{{ansible_distribution_major_version}}" > /etc/yum/vars/dockerosversion
  args:
    creates: /etc/yum/vars/dockerosversion
- name: Install yum-utils
  yum:
    name: yum-utils
    state: present
- name: Install yum repo for DEE 17.06
  shell:
    yum-config-manager --add-repo {{dee_url}}/centos/docker-ee.repo
  args:
    creates: /etc/yum.repos.d/docker-ee.repo
- name: Enable rhel7 extra rpm repo
  shell:
    yum-config-manager --enable centos-extras
- name: Yum Cache Update
  yum:
    list: docker-ee
    update_cache: yes
- name: Install Docker Enterprise Edition
  yum:
    name: docker-ee
    state: latest
- name: Systemd daemon reload
  shell:
    systemctl daemon-reload
- name: Enable Docker Enterprise Engine service
  shell:
    systemctl enable docker.service
- name: Docker Engine Start
  service:
    name: docker.service
    state: started
- name: Check the Docker Enterprise Engine status
  shell:
    systemctl status docker.service
- name: Validate Docker install
  shell:
    docker info
