- name: install enic rpm from a local file
  yum:
    name: /root/kmod-enic-2.3.0.39-rhel7u3.el7.x86_64.rpm
    state: present
  when: ansible_virtualization_type == ""
#- name: Yum Update
#  yum:
#    name: '*'
#    state: latest
- name: Check for reboot hint
  shell: |
    LAST_KERNEL=$(rpm -q --last kernel | perl -pe 's/^kernel-(\S+).*/$1/' | head -1);
    CURRENT_KERNEL=$(uname -r);
    if [ $LAST_KERNEL != $CURRENT_KERNEL ];
    then
       echo 'reboot'; else echo 'no';
    fi
    exit 0
  ignore_errors: true
  register: reboot_hint
- name: Rebooting ...
  shell: sleep 2 && /usr/sbin/reboot
  async: 1
  poll: 0
  ignore_errors: true
  when: reboot_hint.stdout.find("reboot") != -1
- name: Wait for host to boot
  local_action: wait_for
  args:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 360
    timeout: 480
  ignore_errors: true
  when: reboot_hint.stdout.find("reboot") != -1
